context:
  version: "0.1.1"

package:
  name: gwq
  version: ${{ version }}

source:
  url: https://github.com/d-kuro/gwq/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a9c01c670e3a1bf0c3c7d106bbc8ed483916cb94fa67a46542d189b3cb8170d8
  target_directory: src

build:
  number: 0
  script:
    - cd src/cmd/gwq
    - go-licenses save . --save_path ../../../library_licenses
    - if: unix
      then: go build -v -o $PREFIX/bin/gwq -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\gwq.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: gwq --help
  - package_contents:
      bin:
        - gwq
      strict: true

about:
  homepage: https://github.com/d-kuro/gwq
  summary: Summary of the package.
  description: |
    Git worktree manager with fuzzy finder - Work on multiple branches simultaneously, perfect for parallel AI coding workflows
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  documentation: https://github.com/d-kuro/gwq
  repository: https://github.com/d-kuro/gwq

extra:
  recipe-maintainers:
    - denkiwakame
